### ISSUE TITLE
deploying 1.3-beta16 to production issue.

### ISSUE THREAD

**Issue by cj** [practicalmeteor/meteor-mocha#15]
So I've checked and double check, it's starting the app in production mode  https://gist.github.com/2ba114003fcd8cb06707;  but I'm still getting this error https://gist.github.com/0d956727d203225c0a28

**Comment by jsep** [comment]
@cj have you tried this again with 1.3-rc1?

**Comment by TimFletcher** [comment]
I'm getting the same error with 1.3-rc1 deploying to Galaxy

```
2016-03-19 15:14:09-06:00/app/bundle/programs/server/node_modules/fibers/future.js:267
2016-03-19 15:14:09-06:00	throw(ex);
2016-03-19 15:14:09-06:00	^
2016-03-19 15:14:10-06:00TypeError: Cannot call method 'setupGlobals' of undefined
2016-03-19 15:14:10-06:00 at __coffeescriptShare (packages/practicalmeteor_mocha/meteor/src/server/mocha.coffee:9:39)
2016-03-19 15:14:10-06:00 at packages/practicalmeteor_mocha/meteor/src/server/mocha.coffee:1:1
2016-03-19 15:14:10-06:00 at packages/practicalmeteor_mocha/meteor/src/lib/MochaRunner.coffee:1:1
2016-03-19 15:14:10-06:00 at /app/bundle/programs/server/boot.js:245:10
2016-03-19 15:14:10-06:00 at Array.forEach (native)
2016-03-19 15:14:10-06:00 at Function._.each._.forEach (/app/bundle/programs/server/node_modules/underscore/underscore.js:79:11)
2016-03-19 15:14:10-06:00 at /app/bundle/programs/server/boot.js:140:5
```

**Comment by jsep** [comment]
Hi @TimFletcher, make sure you have the latest vesion of the package.

Please add practicalmeteor mocha with version constraint. `meteor add practicalmeteor:mocha@2.1.1-rc.1`. If your using with a package `api.use("practicalmeteor:mocha@2.1.1-rc.1")`

**Comment by TimFletcher** [comment]
Thanks @jsep. It seems to be deploying without any issue on rc1 now.

**Comment by rbabayoff** [comment]
@cj, closing this, for now. Let us now if it doesn't work for you.
